### ISSUE TITLE
exporting error

### ISSUE THREAD

**Issue by Lolita05** [cogitokat/genegraphics#1] opened 2018-12-11 10:23 UTC
Hello!

When I tried to export my graphics, I ran into such a problem. Boot options couldn't uploaded. Tried to do the same with other computers, files, and a browsers, but that didn't work.

<img width="421" alt="2018-12-11 13 10 02" src="https://user-images.githubusercontent.com/40859200/49793363-16fcbb80-fd46-11e8-9257-950549103d49.png">

Any suggestions? :)

**Comment by remizallot** [comment] 2019-01-17 16:07
Hi, 

Can you please try again?

Thanks!

**Comment by ggonnella** [comment] 2019-02-26 18:02
Same for me. Both on your server or downloading the repository and running locally.

**Comment by remizallot** [comment] 2019-03-06 23:07
Hi, 

The problem has been identified.

While the issue is being worked on, a temporary fix has been set up.
If you are not able to export, please retry after a few hours.

Thanks

**Comment by Arzamasov** [comment] 2019-03-14 03:48
Hi,
the export feature is not working for tsv input (Google Chrome + macOS Mojave). Interestingly, it works if I choose tutorial files as input.

**Comment by katlabs** [comment] 2019-03-14 16:50
Hello,
I am making a major update to the exporting process which will be released within a few days. Please be patient. The update should resolve most export errors.

Thanks,
Katherine

**Comment by katlabs** [comment] 2019-03-19 03:49
I made some updates to Gene graphics that should solve most exporting problems. I'm going to close this issue, but if you encounter any further problems, please open another issue with the specific problem. Thanks for your patience!

**Closed as completed by katlabs** 2019-03-19 03:49 UTC
